services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-projeto}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-projeto}
      - POSTGRES_DB=${POSTGRES_DB:-projeto}
    ports:
      - "5432:5432"

  app:
    image: tomasmiele/cloud-projeto:latest
    container_name: fastapi_app
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-projeto}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-projeto}
      - POSTGRES_DB=${POSTGRES_DB:-projeto}
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY:-H456ZLCOCHH7CH10}
    ports:
      - "8000:8000"
    depends_on:
      - db